# Generated by Django 3.1.1 on 2020-09-05 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mountain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mountain',
            old_name='Hallasan',
            new_name='hallasan',
        ),
        migrations.RenameField(
            model_name='mountain',
            old_name='Palgongsan',
            new_name='palgongsan',
        ),
        migrations.RenameField(
            model_name='mountain',
            old_name='Seoraksan',
            new_name='seoraksan',
        ),
    ]
