# Generated by Django 3.1.1 on 2020-09-05 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200905_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mountain',
        ),
    ]
