# Generated by Django 3.1.1 on 2020-09-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='(제목 없음)')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('content', models.TextField(blank=True)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
