# Generated by Django 3.1.1 on 2020-09-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageapp', '0004_mountain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mountain',
        ),
    ]
